= Projet 0

== Objectifs

* Consolider des connaissances de base en programmation et les mettre en oeuvre avec Kotlin

* Concepts de programmation objet

* Initiation aux tests unitaires

* Premier pas en mode projet

== Compétences visées à l'issue des 3 premières semaines

Niveau : *grand débutant*

* savoir définir une classe avec des attributs et constructeur primaire : au moins 2 façons de faire avec Kotlin
* savoir redéfinir les méthodes de la classe mère `Any`
* comprendre le mécanisme des _accesseurs_ lié aux properties (Kotlin)
* savoir déclarer des références à des objets pouvant être null ou non
* savoir définir une méthode et intégrer de la documentation technique (`KDoc`)
* savoir faire la distinction entre définir et appeler une méthode
* savoir interpréter/comprendre du code simple écrit par un autre
* savoir interpréter et concevoir une représentation d'un algorithme simple en UML (diag. d'activités)
* savoir mettre en oeuvre des tests unitaires
* savoir gérer une liste d'objets
* connaitre la différence entre val et var
* Comprendre les différents modes de  passage d'argument à une fonction (par position, par nom)
* savoir déclarer (et utiliser) une fonction en dehors d'une classe
* savoir gérer les structures de contrôle classiques (celle qui ont été étudiées l'année dernière avec php et java)
* savoir utiliser un bon vocabulaire technique
* savoir interpréter et concevoir un diag de classe simple (sans héritage)
* savoir pousser un travail sur gitlab, voire travailler en équipe...
* s'être impliquer dans un travail en mode projet (autonomie, respect des consignes, d'une deadline...)

== Présentation du projet 0

Le projet est sur gitlab : https://gitlab.com/sio-labo/devinelacarte[Devine la carte]

== Livraison

=== Ce qui est attendu

https://gitlab.com/sio-labo/devinelacarte#user-content-livraison[Ce que vous devez produire]

=== Deadline

#mardi 11 octobre 2022 23h59.#
