= Notion de qualité dans le logiciel
:author: Olivier Capuozzo
:docdate: 2022-07-19
:asciidoctor-version:1.1
:description: Des facteurs de qualité du code
:icons: font
:listing-caption: Listing
:toc-title: Table des matières
:toc: left
:toclevels: 4

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


== Présentation

En mars 2020, Google publie https://static.googleusercontent.com/media/landing.google.com/en//sre/static/pdf/SRS.pdf[Building Secure and Reliable Systems].

En préface, le livre démarre par cette question : "_un système peut-il être considéré comme vraiment fiable [reliable] s'il n'est pas fondamentalement sûr [secure] ? Ou peut-il être considéré comme sûr s'il n'est pas fiable ?_".

Cette question nous ramène à la notion de qualité dans le logiciel et ce document présente ici, dans les grandes lignes,
les principaux critèques de qualité et nous invitons le lecteur à approfondir ce thème par l'ouvrage de référence,
sur lequel cette étude est principalement basée, https://www.eyrolles.com/Informatique/Livre/conception-et-programmation-orientees-objet-9782212675009/[Conception et Programmation orientées objet (Bertrand Meyer)].

<<<incude::include/_introduction.adoc[leveloffset=+1]
<<<include::include/_correction.adoc[leveloffset=+1]
<<<include::include/_robustesse.adoc[leveloffset=+1]
<<<include::include/_robustesse-secure.adoc[leveloffset=+1]
<<<include::include/_extensibilite.adoc[leveloffset=+1]
<<<include::include/_reutilisabilite.adoc[leveloffset=+1]
<<<include::include/_compatibilite.adoc[leveloffset=+1]
<<<include::include/_efficacite.adoc[leveloffset=+1]
<<<include::include/_portabilite.adoc[leveloffset=+1]
<<<include::include/_ux.adoc[leveloffset=+1]
<<<include::include/_couverture.adoc[leveloffset=+1]
<<<include::include/_ponctualite.adoc[leveloffset=+1]
<<<include::include/_documentation.adoc[leveloffset=+1]
<<<include::include/_facteurs-contradictoires.adoc[leveloffset=+1]
<<<include::include/_qualites-essentielles.adoc[leveloffset=+1]
<<<include::include/_qualites-XP.adoc[leveloffset=+1]
<<<

